[package]
name = "resonance_input"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
resonance_core = { workspace = true }
bevy_ecs = { workspace = true }
winit = { workspace = true }